### ISSUE TITLE
[BUG - Firefox] navigator.clipboard.readText is not a function

### ISSUE THREAD

**Issue by yancoltro** [oandrewhb/cifra-de-vigenere#1]
**Descrição do problema**
A funcionalidade de colar texto não funciona da maneira esperada no Firefox

Aparantemente o Firefox não é tão permissivo quando o Chrome (por exemplo) para permitir que a aplicação possa ler o clipboard do usuário, e isso acaba gerando um erro quando clicamos no botão

Caso seja útil, talvez a documentação pode fornecer mais detalhes
[MDN - Clipboard: read() method](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText#browser_compatibility)
[MDN - Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API)

Abaixo está um screenshot do problema
![Screenshot from 2023-11-09 00-27-14](https://github.com/oandrewhb/cifra-de-vigenere/assets/31298655/29eda369-1329-4849-a5ec-a77a56955fdb)

**Comment by oandrewhb** [comment]
A princípio eu "resolvi" esse problema validando se as funções de "copiar para o clipboard" e "ler do clipboard" estão disponíveis antes de mostrar os botões "Copiar chave" e "Colar texto" respectivamente.
